import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { open_sans } from "@/assets/fonts/next-fonts";

export const metadata: Metadata = {
  title: "DAWIN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${open_sans.className} flex h-screen flex-col antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
